ClapDetection
std::vector<double> ClapDetection::y_find
std::string ClapDetection::clapSamplePath
std::vector<double> ClapDetection::audioData
bool ClapDetection::recorded
PaError ClapDetection::err
PaStream* ClapDetection::stream
PaStreamParameters ClapDetection::inputParameters
std::vector<double>* ClapDetection::y_findPtr
ClapDetection::ClapDetection()
void ClapDetection::Initialize()
Initializes our Clap Detector. return
References load_audio_file.
void ClapDetection::openStream()
References paCallback.
void ClapDetection::closeStream()
Referenced by detectClap.
void ClapDetection::start()
References find_per_data, paCallback, result.
void ClapDetection::stop() const
Referenced by detectClap.
void ClapDetection::record()
bool ClapDetection::detectClap()
References closeStream, find_per_data, result, stop.
static int ClapDetection::reverse_bits(int num, int bit_length)
References result.
Referenced by fft.
static void ClapDetection::fft(std::vector< std::complex< double > > &a, bool inverse)
References reverse_bits.
Referenced by convolve.
static std::vector< double > ClapDetection::convolve(const std::vector< double > &a, const std::vector< double > &b)
References fft, result.
Referenced by find_per, find_per_data.
static std::vector< double > ClapDetection::load_audio_file(const std::string &filename)
Referenced by find_per, Initialize.
static double ClapDetection::percentage_above_threshold(const std::vector< double > &a, double threshold)
Referenced by find_per, find_per_data.
static double ClapDetection::find_per(const std::string &within_file, const std::string &find_file)
References convolve, load_audio_file, percentage_above_threshold.
static double ClapDetection::find_per_data(const std::vector< double > &within_data, const std::vector< double > &y_find)
References convolve, percentage_above_threshold.
Referenced by detectClap, start.
static bool ClapDetection::result(double per, double check)
Referenced by convolve, detectClap, reverse_bits, start.
static int ClapDetection::paCallback(const void *inputBuffer, void *outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
Referenced by openStream, start.