EventHandler
std::unordered_map< Event, std::vector< std::function< void(std::any)> > > EventHandler::listeners
EventHandler & EventHandler::getInstance()
Referenced by main, RFID::RFID, IntruderMoodDetection::start, RFID::start.
static EventHandler & EventHandler::getInstance()
EventHandler::EventHandler(const EventHandler &)=delete
EventHandler & EventHandler::operator=(const EventHandler &)=delete
void EventHandler::addListener(Event event, std::function< void()> callback)
Referenced by main.
void EventHandler::addListener(Event event, std::function< void(Args...)> callback)
void EventHandler::emit(Event event)
Referenced by main, RFID::RFID, IntruderMoodDetection::start, RFID::start.
void EventHandler::emit(Event event, Args... args)
bool EventHandler::isEventRegistered(Event event) const
EventHandler::EventHandler(const EventHandler &)=delete
EventHandler & EventHandler::operator=(const EventHandler &)=delete
void EventHandler::addListener(Event event, std::function< void()> callback)
void EventHandler::addListener(Event event, std::function< void(Args...)> callback)
void EventHandler::emit(Event event)
void EventHandler::emit(Event event, Args... args)
bool EventHandler::isEventRegistered(Event event) const
EventHandler::EventHandler()=default
EventHandler::~EventHandler()=default
EventHandler::EventHandler()=default
EventHandler::~EventHandler()=default
const char * EventHandler::eventToString(Event event)
static const char * EventHandler::eventToString(Event event)