IntruderMoodDetection
int IntruderMoodDetection::CameraID
Variables for camera
int IntruderMoodDetection::nbins
Globals IntruderMoodDetection::globals
cv::VideoCapture IntruderMoodDetection::masterCamera
cv::Mat IntruderMoodDetection::im
cv::Mat IntruderMoodDetection::gray
cv::Mat IntruderMoodDetection::roi
cv::CascadeClassifier IntruderMoodDetection::detector
std::string IntruderMoodDetection::cascadePath
std::string IntruderMoodDetection::trainedModelPath
cv::Ptr<cv::face::LBPHFaceRecognizer> IntruderMoodDetection::recognizer
std::string IntruderMoodDetection::fileName
std::map<int, std::string> IntruderMoodDetection::users
cv::Ptr<cv::ml::SVM> IntruderMoodDetection::svm
cv::Size IntruderMoodDetection::block_size
cv::Size IntruderMoodDetection::block_stride
cv::Size IntruderMoodDetection::cell_size
cv::HOGDescriptor IntruderMoodDetection::hog
bool IntruderMoodDetection::running
bool IntruderMoodDetection::locked
int IntruderMoodDetection::emits
std::vector<cv::Rect> IntruderMoodDetection::faces
std::map<int, std::string> IntruderMoodDetection::emotion
void IntruderMoodDetection::timerEvent()
IntruderMoodDetection::IntruderMoodDetection()
void IntruderMoodDetection::Initialize(cv::VideoCapture camera)
Initializes our Intruder & Mood Detection. return
References Globals::getMoodSvm, Globals::setMoodSvm.
void IntruderMoodDetection::stop()
References stop.
Referenced by stop, IntruderMoodThread::stop.
void IntruderMoodDetection::start()
References EventHandler::emit, EventHandler::getInstance, readFileToMap.
Referenced by IntruderMoodThread::restart, unlock.
void IntruderMoodDetection::unlock()
References start.
Referenced by IntruderMoodThread::unlock.
std::map< int, std::string > IntruderMoodDetection::readFileToMap(const std::string &fileName)
Referenced by start.
void IntruderMoodDetection::restart()
Referenced by IntruderMoodThread::restart.
void IntruderMoodDetection::setCameraId(int id)
Camera setup functions
void IntruderMoodDetection::setContrasts(int low, int high)
void IntruderMoodDetection::setShutter(int shutter)
int IntruderMoodDetection::checkCameraOpen(cv::VideoCapture camera)
cv::Mat IntruderMoodDetection::takePicture()
Camera functions
void IntruderMoodDetection::savePicture(cv::VideoCapture *, std::string filename)