CppThread
std::thread CppThread::uthread
void CppThread::start()
Starts the thread.
References run.
Referenced by main.
void CppThread::join()
Waits for the thread to terminate.
Referenced by main.
virtual void CppThread::run()=0
This method does all the work of this thread. Overload this abstract function with a real one doing the actual work of this thread.
Referenced by start.