IntruderDatasetCreator
cv::VideoCapture IntruderDatasetCreator::masterCamera
cv::CascadeClassifier IntruderDatasetCreator::detector
std::string IntruderDatasetCreator::cascadePath
std::string IntruderDatasetCreator::fileName
std::string IntruderDatasetCreator::newUser
int IntruderDatasetCreator::samples
int IntruderDatasetCreator::CameraID
cv::Mat IntruderDatasetCreator::gray
std::vector<cv::Rect> IntruderDatasetCreator::faces
void IntruderDatasetCreator::timerEvent()
Timer function for intruder detector's dataset creation functionality.
IntruderDatasetCreator::IntruderDatasetCreator()
Constructor
void IntruderDatasetCreator::Initialize(cv::VideoCapture camera)
Initializes our Dataset Creator. camera Camera object.
References appendLineToFile, findStringInFile, getLastIntegerInFile, is_valid_name, replace_spaces_with_underscores, trim.
void IntruderDatasetCreator::stop()
References stop.
Referenced by stop, IntruderThread::stop.
std::string IntruderDatasetCreator::trim(const std::string &str)
Referenced by Initialize.
int IntruderDatasetCreator::count_name(const std::string &str)
std::string IntruderDatasetCreator::replace_spaces_with_underscores(const std::string &str)
Referenced by Initialize.
bool IntruderDatasetCreator::is_valid_name(const std::string &name)
Referenced by Initialize.
bool IntruderDatasetCreator::findStringInFile(const std::string &fileName, const std::string &searchString)
Referenced by Initialize.
int IntruderDatasetCreator::getLastIntegerInFile(const std::string &fileName)
Referenced by Initialize.
void IntruderDatasetCreator::appendLineToFile(const std::string &fileName, const std::string &line)
Referenced by Initialize.
int IntruderDatasetCreator::checkCameraOpen(cv::VideoCapture camera)