GPIODriver
GPIODriver::GPIODriver(void)
int GPIODriver::SetGPIOState(int gpioPinNumber, int value)
Set state of the GPIO pin. LOW - value = 0 HIGH - value = 1 gpioPinNumber GPIO Pin number state to read. value State to set the pin to. Zero on success else negative error number
References LOW, VALUE_STRING_MAX_LENGTH.
Referenced by RelayBoard::Airflow, RelayBoard::Heating, RelayBoard::Lighting, SetUpPin, RelayBoard::Turn_Relays_Off, RelayBoard::Watering.
int GPIODriver::GPIORead(int gpioPinNumber)
Get the current state of the GPIO pin. LOW = 0 HIGH = 1 gpioPinNumber GPIO Pin number state to read. State of the GPIO Pin
References VALUE_STRING_MAX_LENGTH.
Referenced by RelayBoard::GetAirflowState, RelayBoard::GetHeatingState, RelayBoard::GetLightingState, RelayBoard::GetWateringState.
int GPIODriver::SetUpPin(int gpioPinNumber)
Initialize GPIO Pins for output use. Export Pin Set Direction to output Set GPIO state value to high gpioPinNumber GPIO pin number to set up for output use. Zero on success error
References SetGPIOState.
Referenced by RelayBoard::Initialize.
int GPIODriver::ExportGPIO(int gpioPinNumber)
Export GPIO Pin gpioPinNumber GPIO Pin number to export. Zero on success error
int GPIODriver::UnexportGPIO(int gpioPinNumber)
Unexport GPIO Pin gpioPinNumber GPIO Pin number to unexport. Zero on success error
int GPIODriver::SetGPIODirection(int gpioPinNumber, int direction)
Set Direction of GPIO Pin Input = 0 Output = 1 gpioPinNumber GPIO Pin number to export. direction Direction of the pin. Zero on success error