Globals
cv::Ptr<cv::ml::SVM> Globals::mood_svm
int Globals::garageDoorPin
int Globals::mainDoorPin
int Globals::ledPin
int Globals::ledRedPin
int Globals::ledGreenPin
int Globals::ledBluePin
void Globals::setMoodSvm()
Referenced by IntruderMoodDetection::Initialize, MoodDetection::Initialize.
cv::Ptr< cv::ml::SVM > Globals::getMoodSvm()
Referenced by IntruderMoodDetection::Initialize, MoodDetection::Initialize.
int Globals::getGarageDoorPin()
int Globals::getMainDoorPin()
int Globals::getLedPin()
int Globals::getLedRedPin()
int Globals::getLedGreenPin()
int Globals::getLedBluePin()