spidevpp::Gpio
Direction
Value
const unsigned int spidevpp::Gpio::mPin
const Direction spidevpp::Gpio::mDirection
const std::string spidevpp::Gpio::mDirectionFilePath
const std::string spidevpp::Gpio::mValueFilePath
Value spidevpp::Gpio::mValue
spidevpp::Gpio::Gpio(unsigned int pin, Direction direction, Value initialValue=Value::low)
References setValue.
void spidevpp::Gpio::setValue(Value)
Referenced by Gpio, SysGpio::setValue.
Gpio::Value spidevpp::Gpio::getValue()
References high, low.
Referenced by SysGpio::getValue.