ControllerThread
argvEnum
int ControllerThread::argc
std::vector<std::string> ControllerThread::argv
std::map<std::string, argvEnum> ControllerThread::argvValues
ControllerThread::ControllerThread()
Contructor for our controller thread. All child threads are initiallized here.
void ControllerThread::setArgs(int ac, std::vector< std::string > av)
Referenced by main.
void CppThread::start()
Starts the thread.
References CppThread::run.
Referenced by main.
void CppThread::join()
Waits for the thread to terminate.
Referenced by main.
void ControllerThread::run()
Manage the controller thread runnable.