mfrc522::MFRC522
PCD_Register
PCD_Command
PCD_RxGain
PICC_Command
MIFARE_Misc
PICC_Type
StatusCode
PCD_Register
PCD_Command
PCD_RxGain
PICC_Command
MIFARE_Misc
PICC_Type
StatusCode
Uid mfrc522::MFRC522::uid
Referenced by MIFARE_SetUid, PCD_Authenticate, PICC_DumpMifareClassicSectorToSerial, PICC_DumpMifareClassicToSerial, PICC_DumpToSerial, PICC_ReadCardSerial, PICC_Select, RFID::RFID, RFID::start.
ISpi & mfrc522::MFRC522::mSpi
Referenced by PCD_ReadRegister, PCD_WriteRegister.
IGpio & mfrc522::MFRC522::mResetPin
Referenced by MFRC522, PCD_Init.
static const uint8_t mfrc522::MFRC522::FIFO_SIZE
mfrc522::MFRC522::MFRC522(ISpi &, IGpio &resetPin)
Constructor.
References mfrc522::IGpio::low, mResetPin, mfrc522::IGpio::setValue.
void mfrc522::MFRC522::PCD_WriteRegister(uint8_t reg, uint8_t value)
The register to write to. One of the PCD_Register enums.
Writes a byte to the specified register in the MFRC522 chip. The interface is described in the datasheet section 8.1.2.
References mSpi, mfrc522::ISpi::write.
Referenced by PCD_AntennaOn, PCD_CalculateCRC, PCD_ClearRegisterBitMask, PCD_CommunicateWithPICC, PCD_Init, PCD_PerformSelfTest, PCD_Reset, PCD_SetRegisterBitMask, PCD_WriteRegister, PICC_Select.
void mfrc522::MFRC522::PCD_WriteRegister(uint8_t reg, uint8_t count, uint8_t *values)
The register to write to. One of the PCD_Register enums.
Writes a number of bytes to the specified register in the MFRC522 chip. The interface is described in the datasheet section 8.1.2.
References PCD_WriteRegister.
uint8_t mfrc522::MFRC522::PCD_ReadRegister(uint8_t reg)
The register to read from. One of the PCD_Register enums.
Reads a byte from the specified register in the MFRC522 chip. The interface is described in the datasheet section 8.1.2.
References mSpi, mfrc522::ISpi::writeRead.
Referenced by PCD_AntennaOn, PCD_CalculateCRC, PCD_ClearRegisterBitMask, PCD_CommunicateWithPICC, PCD_GetAntennaGain, PCD_PerformSelfTest, PCD_Reset, PCD_SetRegisterBitMask, PICC_Select.
void mfrc522::MFRC522::PCD_ReadRegister(uint8_t reg, uint8_t count, uint8_t *values, uint8_t rxAlign=0)
The register to read from. One of the PCD_Register enums.
Reads a number of bytes from the specified register in the MFRC522 chip. The interface is described in the datasheet section 8.1.2.
References mSpi, mfrc522::ISpi::writeRead.
void mfrc522::MFRC522::setBitMask(unsigned char reg, unsigned char mask)
void mfrc522::MFRC522::PCD_SetRegisterBitMask(uint8_t reg, uint8_t mask)
The register to update. One of the PCD_Register enums.
Sets the bits given in mask in register reg.
References PCD_ReadRegister, PCD_WriteRegister.
Referenced by PCD_CalculateCRC, PCD_CommunicateWithPICC, PCD_PerformSelfTest, PCD_SetAntennaGain.
void mfrc522::MFRC522::PCD_ClearRegisterBitMask(uint8_t reg, uint8_t mask)
The register to update. One of the PCD_Register enums.
Clears the bits given in mask from register reg.
References PCD_ReadRegister, PCD_WriteRegister.
Referenced by PCD_AntennaOff, PCD_SetAntennaGain, PCD_StopCrypto1, PICC_REQA_or_WUPA, PICC_Select.
uint8_t mfrc522::MFRC522::PCD_CalculateCRC(uint8_t *data, uint8_t length, uint8_t *result)
In: Pointer to the data to transfer to the FIFO for CRC calculation.
Use the CRC coprocessor in the MFRC522 to calculate a CRC_A. STATUS_OK on success, STATUS_??? otherwise.
References CommandReg, CRCResultRegH, CRCResultRegL, DivIrqReg, FIFODataReg, FIFOLevelReg, PCD_CalcCRC, PCD_Idle, PCD_ReadRegister, PCD_SetRegisterBitMask, PCD_WriteRegister, STATUS_OK, STATUS_TIMEOUT.
Referenced by MIFARE_Read, PCD_CommunicateWithPICC, PCD_MIFARE_Transceive, PICC_HaltA, PICC_Select.
void mfrc522::MFRC522::PCD_Init()
Initializes the MFRC522 chip.
References mfrc522::IGpio::high, ModeReg, mResetPin, PCD_AntennaOn, PCD_WriteRegister, mfrc522::IGpio::setValue, TModeReg, TPrescalerReg, TReloadRegH, TReloadRegL, TxASKReg.
Referenced by RFID::RFID.
void mfrc522::MFRC522::PCD_Reset()
Performs a soft reset on the MFRC522 chip and waits for it to be ready again.
References CommandReg, PCD_ReadRegister, PCD_SoftReset, PCD_WriteRegister.
Referenced by PCD_PerformSelfTest.
void mfrc522::MFRC522::PCD_AntennaOn()
Turns the antenna on by enabling pins TX1 and TX2. After a reset these pins are disabled.
References PCD_ReadRegister, PCD_WriteRegister, TxControlReg.
Referenced by PCD_Init.
void mfrc522::MFRC522::PCD_AntennaOff()
Turns the antenna off by disabling pins TX1 and TX2.
References PCD_ClearRegisterBitMask, TxControlReg.
uint8_t mfrc522::MFRC522::PCD_GetAntennaGain()
Get the current MFRC522 Receiver Gain (RxGain[2:0]) value. See 9.3.3.6 / table 98 in http://www.nxp.com/documents/data_sheet/MFRC522.pdf NOTE: Return value scrubbed with (0x07<<4)=01110000b as RCFfgReg may use reserved bits. Value of the RxGain, scrubbed to the 3 bits used.
References PCD_ReadRegister, RFCfgReg.
Referenced by PCD_SetAntennaGain.
void mfrc522::MFRC522::PCD_SetAntennaGain(uint8_t mask)
Set the MFRC522 Receiver Gain (RxGain) to value specified by given mask. See 9.3.3.6 / table 98 in http://www.nxp.com/documents/data_sheet/MFRC522.pdf NOTE: Given mask is scrubbed with (0x07<<4)=01110000b as RCFfgReg may use reserved bits.
References PCD_ClearRegisterBitMask, PCD_GetAntennaGain, PCD_SetRegisterBitMask, RFCfgReg.
bool mfrc522::MFRC522::PCD_PerformSelfTest()
Performs a self-test of the MFRC522 See 16.1.1 in http://www.nxp.com/documents/data_sheet/MFRC522.pdf Whether or not the test passed.
References AutoTestReg, CommandReg, DivIrqReg, FIFODataReg, FIFOLevelReg, mfrc522::MFRC522_firmware_referenceV1_0, mfrc522::MFRC522_firmware_referenceV2_0, PCD_CalcCRC, PCD_Idle, PCD_Mem, PCD_ReadRegister, PCD_Reset, PCD_SetRegisterBitMask, PCD_WriteRegister, VersionReg.
uint8_t mfrc522::MFRC522::PCD_TransceiveData(uint8_t *sendData, uint8_t sendLen, uint8_t *backData, uint8_t *backLen, uint8_t *validBits=NULL, uint8_t rxAlign=0, bool checkCRC=false)
Pointer to the data to transfer to the FIFO.
Executes the Transceive command. CRC validation can only be done if backData and backLen are specified. STATUS_OK on success, STATUS_??? otherwise.
References PCD_CommunicateWithPICC, PCD_Transceive.
Referenced by MIFARE_OpenUidBackdoor, MIFARE_Read, PICC_HaltA, PICC_REQA_or_WUPA, PICC_Select.
uint8_t mfrc522::MFRC522::PCD_CommunicateWithPICC(uint8_t command, uint8_t waitIRq, uint8_t *sendData, uint8_t sendLen, uint8_t *backData=NULL, uint8_t *backLen=NULL, uint8_t *validBits=NULL, uint8_t rxAlign=0, bool checkCRC=false)
The command to execute. One of the PCD_Command enums.
Transfers data to the MFRC522 FIFO, executes a command, waits for completion and transfers data back from the FIFO. CRC validation can only be done if backData and backLen are specified. STATUS_OK on success, STATUS_??? otherwise.
References BitFramingReg, ComIrqReg, CommandReg, ControlReg, ErrorReg, FIFODataReg, FIFOLevelReg, PCD_CalculateCRC, PCD_Idle, PCD_ReadRegister, PCD_SetRegisterBitMask, PCD_Transceive, PCD_WriteRegister, STATUS_COLLISION, STATUS_CRC_WRONG, STATUS_ERROR, STATUS_MIFARE_NACK, STATUS_NO_ROOM, STATUS_OK, STATUS_TIMEOUT.
Referenced by PCD_Authenticate, PCD_MIFARE_Transceive, PCD_TransceiveData.
uint8_t mfrc522::MFRC522::PICC_RequestA(uint8_t *bufferATQA, uint8_t *bufferSize)
The buffer to store the ATQA (Answer to request) in
Transmits a REQuest command, Type A. Invites PICCs in state IDLE to go to READY and prepare for anticollision or selection. 7 bit frame. Beware: When two PICCs are in the field at the same time I often get STATUS_TIMEOUT - probably due do bad antenna design. STATUS_OK on success, STATUS_??? otherwise.
References PICC_CMD_REQA, PICC_REQA_or_WUPA.
Referenced by PICC_IsNewCardPresent.
uint8_t mfrc522::MFRC522::PICC_WakeupA(uint8_t *bufferATQA, uint8_t *bufferSize)
The buffer to store the ATQA (Answer to request) in
Transmits a Wake-UP command, Type A. Invites PICCs in state IDLE and HALT to go to READY(*) and prepare for anticollision or selection. 7 bit frame. Beware: When two PICCs are in the field at the same time I often get STATUS_TIMEOUT - probably due do bad antenna design. STATUS_OK on success, STATUS_??? otherwise.
References PICC_CMD_WUPA, PICC_REQA_or_WUPA.
Referenced by MIFARE_SetUid.
uint8_t mfrc522::MFRC522::PICC_REQA_or_WUPA(uint8_t command, uint8_t *bufferATQA, uint8_t *bufferSize)
The command to send - PICC_CMD_REQA or PICC_CMD_WUPA
Transmits REQA or WUPA commands. Beware: When two PICCs are in the field at the same time I often get STATUS_TIMEOUT - probably due do bad antenna design. STATUS_OK on success, STATUS_??? otherwise.
References CollReg, PCD_ClearRegisterBitMask, PCD_TransceiveData, STATUS_ERROR, STATUS_NO_ROOM, STATUS_OK.
Referenced by PICC_RequestA, PICC_WakeupA.
uint8_t mfrc522::MFRC522::PICC_Select(Uid *uid, uint8_t validBits=0)
Pointer to Uid struct. Normally output, but can also be used to supply a known UID.
Transmits SELECT/ANTICOLLISION commands to select a single PICC. Before calling this function the PICCs must be placed in the READY(*) state by calling PICC_RequestA() or PICC_WakeupA(). On success: The chosen PICC is in state ACTIVE(*) and all other PICCs have returned to state IDLE/HALT. (Figure 7 of the ISO/IEC 14443-3 draft.) The UID size and value of the chosen PICC is returned in *uid along with the SAK. A PICC UID consists of 4, 7 or 10 bytes. Only 4 bytes can be specified in a SELECT command, so for the longer UIDs two or three iterations are used: UID size Number of UID bytes Cascade levels Example of PICC ======== =================== ============== =============== single 4 1 MIFARE Classic double 7 2 MIFARE Ultralight triple 10 3 Not currently in use? STATUS_OK on success, STATUS_??? otherwise.
References BitFramingReg, CollReg, PCD_CalculateCRC, PCD_ClearRegisterBitMask, PCD_ReadRegister, PCD_TransceiveData, PCD_WriteRegister, PICC_CMD_CT, PICC_CMD_SEL_CL1, PICC_CMD_SEL_CL2, PICC_CMD_SEL_CL3, mfrc522::MFRC522::Uid::sak, mfrc522::MFRC522::Uid::size, STATUS_COLLISION, STATUS_CRC_WRONG, STATUS_ERROR, STATUS_INTERNAL_ERROR, STATUS_INVALID, STATUS_OK, uid, mfrc522::MFRC522::Uid::uidByte.
Referenced by PICC_ReadCardSerial.
uint8_t mfrc522::MFRC522::PICC_HaltA()
Instructs a PICC in state ACTIVE(*) to go to state HALT. STATUS_OK on success, STATUS_??? otherwise.
References PCD_CalculateCRC, PCD_TransceiveData, PICC_CMD_HLTA, STATUS_ERROR, STATUS_OK, STATUS_TIMEOUT.
Referenced by MIFARE_OpenUidBackdoor, PICC_DumpMifareClassicToSerial, PICC_DumpToSerial.
uint8_t mfrc522::MFRC522::PCD_Authenticate(uint8_t command, uint8_t blockAddr, MIFARE_Key *key, Uid *uid)
PICC_CMD_MF_AUTH_KEY_A or PICC_CMD_MF_AUTH_KEY_B
Executes the MFRC522 MFAuthent command. This command manages MIFARE authentication to enable a secure communication to any MIFARE Mini, MIFARE 1K and MIFARE 4K card. The authentication is described in the MFRC522 datasheet section 10.3.1.9 and http://www.nxp.com/documents/data_sheet/MF1S503x.pdf section 10.1. For use with MIFARE Classic PICCs. The PICC must be selected - ie in state ACTIVE(*) - before calling this function. Remember to call PCD_StopCrypto1() after communicating with the authenticated PICC - otherwise no new communications can start. All keys are set to FFFFFFFFFFFFh at chip delivery. STATUS_OK on success, STATUS_??? otherwise. Probably STATUS_TIMEOUT if you supply the wrong key.
References mfrc522::MFRC522::MIFARE_Key::keyByte, MF_KEY_SIZE, PCD_CommunicateWithPICC, PCD_MFAuthent, uid, mfrc522::MFRC522::Uid::uidByte.
Referenced by MIFARE_SetUid, PICC_DumpMifareClassicSectorToSerial.
void mfrc522::MFRC522::PCD_StopCrypto1()
Used to exit the PCD from its authenticated state. Remember to call this function after communicating with an authenticated PICC - otherwise no new communications can start.
References PCD_ClearRegisterBitMask, Status2Reg.
Referenced by MIFARE_SetUid, PICC_DumpMifareClassicToSerial.
uint8_t mfrc522::MFRC522::MIFARE_Read(uint8_t blockAddr, uint8_t *buffer, uint8_t *bufferSize)
MIFARE Classic: The block (0-0xff) number. MIFARE Ultralight: The first page to return data from.
Reads 16 bytes (+ 2 bytes CRC_A) from the active PICC. For MIFARE Classic the sector containing the block must be authenticated before calling this function. For MIFARE Ultralight only addresses 00h to 0Fh are decoded. The MF0ICU1 returns a NAK for higher addresses. The MF0ICU1 responds to the READ command by sending 16 bytes starting from the page address defined by the command argument. For example; if blockAddr is 03h then pages 03h, 04h, 05h, 06h are returned. A roll-back is implemented: If blockAddr is 0Eh, then the contents of pages 0Eh, 0Fh, 00h and 01h are returned. The buffer must be at least 18 bytes because a CRC_A is also returned. Checks the CRC_A before returning STATUS_OK. STATUS_OK on success, STATUS_??? otherwise.
References PCD_CalculateCRC, PCD_TransceiveData, PICC_CMD_MF_READ, STATUS_NO_ROOM, STATUS_OK.
Referenced by MIFARE_GetValue, MIFARE_SetUid, PICC_DumpMifareClassicSectorToSerial, PICC_DumpMifareUltralightToSerial.
uint8_t mfrc522::MFRC522::MIFARE_Write(uint8_t blockAddr, uint8_t *buffer, uint8_t bufferSize)
MIFARE Classic: The block (0-0xff) number. MIFARE Ultralight: The page (2-15) to write to.
Writes 16 bytes to the active PICC. For MIFARE Classic the sector containing the block must be authenticated before calling this function. For MIFARE Ultralight the operation is called "COMPATIBILITY WRITE". Even though 16 bytes are transferred to the Ultralight PICC, only the least significant 4 bytes (bytes 0 to 3) are written to the specified address. It is recommended to set the remaining bytes 04h to 0Fh to all logic 0. STATUS_OK on success, STATUS_??? otherwise.
References PCD_MIFARE_Transceive, PICC_CMD_MF_WRITE, STATUS_INVALID, STATUS_OK.
Referenced by MIFARE_SetUid, MIFARE_SetValue, MIFARE_UnbrickUidSector.
uint8_t mfrc522::MFRC522::MIFARE_Decrement(uint8_t blockAddr, long delta)
The block (0-0xff) number.
MIFARE Decrement subtracts the delta from the value of the addressed block, and stores the result in a volatile memory. For MIFARE Classic only. The sector containing the block must be authenticated before calling this function. Only for blocks in "value block" mode, ie with access bits [C1 C2 C3] = [110] or [001]. Use MIFARE_Transfer() to store the result in a block. STATUS_OK on success, STATUS_??? otherwise.
References PICC_CMD_MF_DECREMENT.
uint8_t mfrc522::MFRC522::MIFARE_Increment(uint8_t blockAddr, long delta)
The block (0-0xff) number.
MIFARE Increment adds the delta to the value of the addressed block, and stores the result in a volatile memory. For MIFARE Classic only. The sector containing the block must be authenticated before calling this function. Only for blocks in "value block" mode, ie with access bits [C1 C2 C3] = [110] or [001]. Use MIFARE_Transfer() to store the result in a block. STATUS_OK on success, STATUS_??? otherwise.
References PICC_CMD_MF_INCREMENT.
uint8_t mfrc522::MFRC522::MIFARE_Restore(uint8_t blockAddr)
The block (0-0xff) number.
MIFARE Restore copies the value of the addressed block into a volatile memory. For MIFARE Classic only. The sector containing the block must be authenticated before calling this function. Only for blocks in "value block" mode, ie with access bits [C1 C2 C3] = [110] or [001]. Use MIFARE_Transfer() to store the result in a block. STATUS_OK on success, STATUS_??? otherwise.
References PICC_CMD_MF_RESTORE.
uint8_t mfrc522::MFRC522::MIFARE_Transfer(uint8_t blockAddr)
The block (0-0xff) number.
MIFARE Transfer writes the value stored in the volatile memory into one MIFARE Classic block. For MIFARE Classic only. The sector containing the block must be authenticated before calling this function. Only for blocks in "value block" mode, ie with access bits [C1 C2 C3] = [110] or [001]. STATUS_OK on success, STATUS_??? otherwise.
References PCD_MIFARE_Transceive, PICC_CMD_MF_TRANSFER, STATUS_OK.
uint8_t mfrc522::MFRC522::MIFARE_Ultralight_Write(uint8_t page, uint8_t *buffer, uint8_t bufferSize)
The page (2-15) to write to.
Writes a 4 byte page to the active MIFARE Ultralight PICC. STATUS_OK on success, STATUS_??? otherwise.
References PCD_MIFARE_Transceive, PICC_CMD_UL_WRITE, STATUS_INVALID, STATUS_OK.
uint8_t mfrc522::MFRC522::MIFARE_GetValue(uint8_t blockAddr, long *value)
Helper routine to read the current value from a Value Block. Only for MIFARE Classic and only for blocks in "value block" mode, that is: with access bits [C1 C2 C3] = [110] or [001]. The sector containing the block must be authenticated before calling this function. blockAddr The block (0x00-0xff) number. value Current value of the Value Block. STATUS_OK on success, STATUS_??? otherwise.
References MIFARE_Read, STATUS_OK.
uint8_t mfrc522::MFRC522::MIFARE_SetValue(uint8_t blockAddr, long value)
Helper routine to write a specific value into a Value Block. Only for MIFARE Classic and only for blocks in "value block" mode, that is: with access bits [C1 C2 C3] = [110] or [001]. The sector containing the block must be authenticated before calling this function. blockAddr The block (0x00-0xff) number. value New value of the Value Block. STATUS_OK on success, STATUS_??? otherwise.
References MIFARE_Write.
uint8_t mfrc522::MFRC522::PCD_MIFARE_Transceive(uint8_t *sendData, uint8_t sendLen, bool acceptTimeout=false)
Pointer to the data to transfer to the FIFO. Do NOT include the CRC_A.
Wrapper for MIFARE protocol communication. Adds CRC_A, executes the Transceive command and checks that the response is MF_ACK or a timeout. STATUS_OK on success, STATUS_??? otherwise.
References MF_ACK, PCD_CalculateCRC, PCD_CommunicateWithPICC, PCD_Transceive, STATUS_ERROR, STATUS_INVALID, STATUS_MIFARE_NACK, STATUS_OK, STATUS_TIMEOUT.
Referenced by MIFARE_Transfer, MIFARE_Ultralight_Write, MIFARE_Write.
const string mfrc522::MFRC522::GetStatusCodeName(uint8_t code)
One of the StatusCode enums.
Returns a __FlashStringHelper pointer to a status code name.
References STATUS_COLLISION, STATUS_CRC_WRONG, STATUS_ERROR, STATUS_INTERNAL_ERROR, STATUS_INVALID, STATUS_MIFARE_NACK, STATUS_NO_ROOM, STATUS_OK, STATUS_TIMEOUT.
Referenced by MIFARE_OpenUidBackdoor, MIFARE_SetUid, MIFARE_UnbrickUidSector, PICC_DumpMifareClassicSectorToSerial, PICC_DumpMifareUltralightToSerial.
uint8_t mfrc522::MFRC522::PICC_GetType(uint8_t sak)
The SAK byte returned from PICC_Select().
Translates the SAK (Select Acknowledge) to a PICC type. PICC_Type
References PICC_TYPE_ISO_14443_4, PICC_TYPE_ISO_18092, PICC_TYPE_MIFARE_1K, PICC_TYPE_MIFARE_4K, PICC_TYPE_MIFARE_MINI, PICC_TYPE_MIFARE_PLUS, PICC_TYPE_MIFARE_UL, PICC_TYPE_NOT_COMPLETE, PICC_TYPE_TNP3XXX, PICC_TYPE_UNKNOWN.
Referenced by PICC_DumpToSerial.
const string mfrc522::MFRC522::PICC_GetTypeName(uint8_t type)
One of the PICC_Type enums.
Returns a String pointer to the PICC type name.
References PICC_TYPE_ISO_14443_4, PICC_TYPE_ISO_18092, PICC_TYPE_MIFARE_1K, PICC_TYPE_MIFARE_4K, PICC_TYPE_MIFARE_MINI, PICC_TYPE_MIFARE_PLUS, PICC_TYPE_MIFARE_UL, PICC_TYPE_NOT_COMPLETE, PICC_TYPE_TNP3XXX, PICC_TYPE_UNKNOWN.
Referenced by PICC_DumpToSerial.
void mfrc522::MFRC522::PICC_DumpToSerial(Uid *uid)
Pointer to Uid struct returned from a successful PICC_Select().
Dumps debug info about the selected PICC to Serial. On success the PICC is halted after dumping the data. For MIFARE Classic the factory default key of 0xFFFFFFFFFFFF is tried.
References mfrc522::MFRC522::MIFARE_Key::keyByte, PICC_DumpMifareClassicToSerial, PICC_DumpMifareUltralightToSerial, PICC_GetType, PICC_GetTypeName, PICC_HaltA, PICC_TYPE_ISO_14443_4, PICC_TYPE_ISO_18092, PICC_TYPE_MIFARE_1K, PICC_TYPE_MIFARE_4K, PICC_TYPE_MIFARE_MINI, PICC_TYPE_MIFARE_PLUS, PICC_TYPE_MIFARE_UL, PICC_TYPE_NOT_COMPLETE, PICC_TYPE_TNP3XXX, PICC_TYPE_UNKNOWN, mfrc522::MFRC522::Uid::sak, mfrc522::MFRC522::Uid::size, uid, mfrc522::MFRC522::Uid::uidByte.
void mfrc522::MFRC522::PICC_DumpMifareClassicToSerial(Uid *uid, uint8_t piccType, MIFARE_Key *key)
Pointer to Uid struct returned from a successful PICC_Select().
Dumps memory contents of a MIFARE Classic PICC. On success the PICC is halted after dumping the data.
References PCD_StopCrypto1, PICC_DumpMifareClassicSectorToSerial, PICC_HaltA, PICC_TYPE_MIFARE_1K, PICC_TYPE_MIFARE_4K, PICC_TYPE_MIFARE_MINI, uid.
Referenced by PICC_DumpToSerial.
void mfrc522::MFRC522::PICC_DumpMifareClassicSectorToSerial(Uid *uid, MIFARE_Key *key, uint8_t sector)
Pointer to Uid struct returned from a successful PICC_Select().
Dumps memory contents of a sector of a MIFARE Classic PICC. Uses PCD_Authenticate(), MIFARE_Read() and PCD_StopCrypto1. Always uses PICC_CMD_MF_AUTH_KEY_A because only Key A can always read the sector trailer access bits.
References GetStatusCodeName, MIFARE_Read, PCD_Authenticate, PICC_CMD_MF_AUTH_KEY_A, STATUS_OK, uid.
Referenced by PICC_DumpMifareClassicToSerial.
void mfrc522::MFRC522::PICC_DumpMifareUltralightToSerial()
Dumps memory contents of a MIFARE Ultralight PICC.
References GetStatusCodeName, MIFARE_Read, STATUS_OK.
Referenced by PICC_DumpToSerial.
void mfrc522::MFRC522::MIFARE_SetAccessBits(uint8_t *accessBitBuffer, uint8_t g0, uint8_t g1, uint8_t g2, uint8_t g3)
Pointer to byte 6, 7 and 8 in the sector trailer. Bytes [0..2] will be set.
Calculates the bit pattern needed for the specified access bits. In the [C1 C2 C3] tupples C1 is MSB (=4) and C3 is LSB (=1).
bool mfrc522::MFRC522::MIFARE_OpenUidBackdoor(bool logErrors)
Performs the "magic sequence" needed to get Chinese UID changeable Mifare cards to allow writing to sector 0, where the card UID is stored. Note that you do not need to have selected the card through REQA or WUPA, this sequence works immediately when the card is in the reader vicinity. This means you can use this method even on "bricked" cards that your reader does not recognise anymore (see MFRC522::MIFARE_UnbrickUidSector). Of course with non-bricked devices, you're free to select them before calling this function.
References GetStatusCodeName, PCD_TransceiveData, PICC_HaltA, STATUS_OK.
Referenced by MIFARE_SetUid, MIFARE_UnbrickUidSector.
bool mfrc522::MFRC522::MIFARE_SetUid(uint8_t *newUid, uint8_t uidSize, bool logErrors)
Reads entire block 0, including all manufacturer data, and overwrites that block with the new UID, a freshly calculated BCC, and the original manufacturer data. It assumes a default KEY A of 0xFFFFFFFFFFFF. Make sure to have selected the card before this function is called.
References GetStatusCodeName, MIFARE_OpenUidBackdoor, MIFARE_Read, MIFARE_Write, PCD_Authenticate, PCD_StopCrypto1, PICC_CMD_MF_AUTH_KEY_A, PICC_IsNewCardPresent, PICC_ReadCardSerial, PICC_WakeupA, STATUS_OK, STATUS_TIMEOUT, uid.
bool mfrc522::MFRC522::MIFARE_UnbrickUidSector(bool logErrors)
Resets entire sector 0 to zeroes, so the card can be read again by readers.
References GetStatusCodeName, MIFARE_OpenUidBackdoor, MIFARE_Write, STATUS_OK.
bool mfrc522::MFRC522::PICC_IsNewCardPresent()
Returns true if a PICC responds to PICC_CMD_REQA. Only "new" cards in state IDLE are invited. Sleeping cards in state HALT are ignored. bool
References PICC_RequestA, STATUS_COLLISION, STATUS_OK.
Referenced by MIFARE_SetUid, RFID::RFID, RFID::start.
bool mfrc522::MFRC522::PICC_ReadCardSerial()
Simple wrapper around PICC_Select. Returns true if a UID could be read. Remember to call PICC_IsNewCardPresent(), PICC_RequestA() or PICC_WakeupA() first. The read UID is available in the class variable uid. bool
References PICC_Select, STATUS_OK, uid.
Referenced by MIFARE_SetUid, RFID::RFID, RFID::start.
mfrc522::MFRC522::MFRC522(ISpi &, IGpio &resetPin)
void mfrc522::MFRC522::PCD_WriteRegister(uint8_t reg, uint8_t value)
void mfrc522::MFRC522::PCD_WriteRegister(uint8_t reg, uint8_t count, uint8_t *values)
uint8_t mfrc522::MFRC522::PCD_ReadRegister(uint8_t reg)
void mfrc522::MFRC522::PCD_ReadRegister(uint8_t reg, uint8_t count, uint8_t *values, uint8_t rxAlign=0)
void mfrc522::MFRC522::setBitMask(unsigned char reg, unsigned char mask)
void mfrc522::MFRC522::PCD_SetRegisterBitMask(uint8_t reg, uint8_t mask)
void mfrc522::MFRC522::PCD_ClearRegisterBitMask(uint8_t reg, uint8_t mask)
uint8_t mfrc522::MFRC522::PCD_CalculateCRC(uint8_t *data, uint8_t length, uint8_t *result)
void mfrc522::MFRC522::PCD_Init()
void mfrc522::MFRC522::PCD_Reset()
void mfrc522::MFRC522::PCD_AntennaOn()
void mfrc522::MFRC522::PCD_AntennaOff()
uint8_t mfrc522::MFRC522::PCD_GetAntennaGain()
void mfrc522::MFRC522::PCD_SetAntennaGain(uint8_t mask)
bool mfrc522::MFRC522::PCD_PerformSelfTest()
uint8_t mfrc522::MFRC522::PCD_TransceiveData(uint8_t *sendData, uint8_t sendLen, uint8_t *backData, uint8_t *backLen, uint8_t *validBits=NULL, uint8_t rxAlign=0, bool checkCRC=false)
uint8_t mfrc522::MFRC522::PCD_CommunicateWithPICC(uint8_t command, uint8_t waitIRq, uint8_t *sendData, uint8_t sendLen, uint8_t *backData=NULL, uint8_t *backLen=NULL, uint8_t *validBits=NULL, uint8_t rxAlign=0, bool checkCRC=false)
uint8_t mfrc522::MFRC522::PICC_RequestA(uint8_t *bufferATQA, uint8_t *bufferSize)
uint8_t mfrc522::MFRC522::PICC_WakeupA(uint8_t *bufferATQA, uint8_t *bufferSize)
uint8_t mfrc522::MFRC522::PICC_REQA_or_WUPA(uint8_t command, uint8_t *bufferATQA, uint8_t *bufferSize)
uint8_t mfrc522::MFRC522::PICC_Select(Uid *uid, uint8_t validBits=0)
uint8_t mfrc522::MFRC522::PICC_HaltA()
uint8_t mfrc522::MFRC522::PCD_Authenticate(uint8_t command, uint8_t blockAddr, MIFARE_Key *key, Uid *uid)
void mfrc522::MFRC522::PCD_StopCrypto1()
uint8_t mfrc522::MFRC522::MIFARE_Read(uint8_t blockAddr, uint8_t *buffer, uint8_t *bufferSize)
uint8_t mfrc522::MFRC522::MIFARE_Write(uint8_t blockAddr, uint8_t *buffer, uint8_t bufferSize)
uint8_t mfrc522::MFRC522::MIFARE_Decrement(uint8_t blockAddr, long delta)
uint8_t mfrc522::MFRC522::MIFARE_Increment(uint8_t blockAddr, long delta)
uint8_t mfrc522::MFRC522::MIFARE_Restore(uint8_t blockAddr)
uint8_t mfrc522::MFRC522::MIFARE_Transfer(uint8_t blockAddr)
uint8_t mfrc522::MFRC522::MIFARE_Ultralight_Write(uint8_t page, uint8_t *buffer, uint8_t bufferSize)
uint8_t mfrc522::MFRC522::MIFARE_GetValue(uint8_t blockAddr, long *value)
uint8_t mfrc522::MFRC522::MIFARE_SetValue(uint8_t blockAddr, long value)
uint8_t mfrc522::MFRC522::PCD_MIFARE_Transceive(uint8_t *sendData, uint8_t sendLen, bool acceptTimeout=false)
const string mfrc522::MFRC522::GetStatusCodeName(uint8_t code)
uint8_t mfrc522::MFRC522::PICC_GetType(uint8_t sak)
const string mfrc522::MFRC522::PICC_GetTypeName(uint8_t type)
void mfrc522::MFRC522::PICC_DumpToSerial(Uid *uid)
void mfrc522::MFRC522::PICC_DumpMifareClassicToSerial(Uid *uid, uint8_t piccType, MIFARE_Key *key)
void mfrc522::MFRC522::PICC_DumpMifareClassicSectorToSerial(Uid *uid, MIFARE_Key *key, uint8_t sector)
void mfrc522::MFRC522::PICC_DumpMifareUltralightToSerial()
void mfrc522::MFRC522::MIFARE_SetAccessBits(uint8_t *accessBitBuffer, uint8_t g0, uint8_t g1, uint8_t g2, uint8_t g3)
bool mfrc522::MFRC522::MIFARE_OpenUidBackdoor(bool logErrors)
bool mfrc522::MFRC522::MIFARE_SetUid(uint8_t *newUid, uint8_t uidSize, bool logErrors)
bool mfrc522::MFRC522::MIFARE_UnbrickUidSector(bool logErrors)
bool mfrc522::MFRC522::PICC_IsNewCardPresent()
bool mfrc522::MFRC522::PICC_ReadCardSerial()
uint8_t mfrc522::MFRC522::MIFARE_TwoStepHelper(uint8_t command, uint8_t blockAddr, long data)
The command to use
Helper function for the two-step MIFARE Classic protocol operations Decrement, Increment and Restore. STATUS_OK on success, STATUS_??? otherwise.
uint8_t mfrc522::MFRC522::MIFARE_TwoStepHelper(uint8_t command, uint8_t blockAddr, long data)