spidevpp::Spi
const std::string spidevpp::Spi::mDevice
int spidevpp::Spi::mFd
uint8_t spidevpp::Spi::mBitsPerWord
std::chrono::microseconds spidevpp::Spi::mDelay
uint32_t spidevpp::Spi::mMode
uint32_t spidevpp::Spi::mSpeed
spidevpp::Spi::Spi(const std::string &device)
void spidevpp::Spi::setBitsPerWord(uint8_t bitsPerWord)
Referenced by main, RFID::RFID.
uint8_t spidevpp::Spi::getBitsPerWord() const
void spidevpp::Spi::setSpeed(uint32_t speed)
Referenced by main, RFID::RFID.
uint32_t spidevpp::Spi::getSpeed() const
void spidevpp::Spi::setMode(uint32_t mode)
Referenced by RFID::RFID.
uint32_t spidevpp::Spi::getMode() const
void spidevpp::Spi::setDelay(std::chrono::microseconds)
std::chrono::microseconds spidevpp::Spi::getDelay() const
void spidevpp::Spi::write(char *pData, size_t len)
Referenced by main, Spidev::write.
void spidevpp::Spi::read(char *pData, size_t len)
Referenced by main, Spidev::read.
void spidevpp::Spi::writeRead(char *pData, size_t len)
Referenced by main, Spidev::writeRead, writeRead.
char spidevpp::Spi::writeRead(char data)
References writeRead.
Stream & operator<<(Stream &out, const Spi &)