.TH "AudioRecordThread" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioRecordThread
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AudioRecordThread\&.h>\fP
.PP
Inherits \fBCppThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioRecordThread\fP (\fBClapDetection\fP *clapDetection)"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBjoin\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioRecordThread::AudioRecordThread (\fBClapDetection\fP * clapDetection)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CppThread::join ()\fC [inline]\fP, \fC [inherited]\fP"
Waits for the thread to terminate\&. 
.SS "void CppThread::start ()\fC [inline]\fP, \fC [inherited]\fP"
Starts the thread\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
