.TH "src/thread/clap-detection/AudioRecordThread.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/thread/clap-detection/AudioRecordThread.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./CppThread\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./utils/Globals\&.h'\fP
.br
\fC#include 'ClapDetection\&.h'\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAudioRecordThread\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Chinmay Nagrale 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
Handle our audio record thread\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
