.TH "src/peripherals/bcm2835/bcm2835_gpio_impl.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/bcm2835/bcm2835_gpio_impl.h
.SH SYNOPSIS
.br
.PP
\fC#include 'igpio\&.h'\fP
.br
\fC#include 'bcm2835\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBcmGpio\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
