.TH "src Directory Reference" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBclap\-detection\fP"
.br
.ti -1c
.RI "directory \fBcontroller\fP"
.br
.ti -1c
.RI "directory \fBdependencies\fP"
.br
.ti -1c
.RI "directory \fBintruder\-detection\fP"
.br
.ti -1c
.RI "directory \fBintruder\-mood\-detection\fP"
.br
.ti -1c
.RI "directory \fBmood\-detection\fP"
.br
.ti -1c
.RI "directory \fBperipherals\fP"
.br
.ti -1c
.RI "directory \fBthread\fP"
.br
.ti -1c
.RI "directory \fButils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
