.TH "src/peripherals/bcm2835 Directory Reference" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/bcm2835 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbcm2835_gpio_impl\&.h\fP"
.br
.ti -1c
.RI "file \fBbcm2835_spi_impl\&.h\fP"
.br
.ti -1c
.RI "file \fBigpio\&.h\fP"
.br
.ti -1c
.RI "file \fBispi\&.h\fP"
.br
.in -1c
