.TH "src/dependencies/spidevpp/apps/loopback_example_app Directory Reference" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dependencies/spidevpp/apps/loopback_example_app Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cc\fP"
.br
.in -1c
