.TH "src/dependencies/spidevpp/libs/spidevpp Directory Reference" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dependencies/spidevpp/libs/spidevpp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgpio\&.cc\fP"
.br
.ti -1c
.RI "file \fBgpio\&.h\fP"
.br
.ti -1c
.RI "file \fBspi\&.cc\fP"
.br
.ti -1c
.RI "file \fBspi\&.h\fP"
.br
.in -1c
