.TH "src/peripherals/spi Directory Reference" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/spi Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBspidev_impl\&.h\fP"
.br
.ti -1c
.RI "file \fBsys_gpio_impl\&.h\fP"
.br
.in -1c
