.TH "src/peripherals Directory Reference" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbcm2835\fP"
.br
.ti -1c
.RI "directory \fBspi\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCamera\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCamera\&.h\fP"
.br
.ti -1c
.RI "file \fBGPIODriver\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGPIODriver\&.h\fP"
.br
.ti -1c
.RI "file \fBI2CDriver\&.cpp\fP"
.br
.ti -1c
.RI "file \fBI2CDriver\&.h\fP"
.br
.ti -1c
.RI "file \fBI2CSensor\&.h\fP"
.br
.ti -1c
.RI "file \fBLEDController\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLEDController\&.h\fP"
.br
.ti -1c
.RI "file \fBMFRC522\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMFRC522\&.h\fP"
.br
.ti -1c
.RI "file \fBRelayBoard\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRelayBoard\&.h\fP"
.br
.ti -1c
.RI "file \fBRFID\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRFID\&.h\fP"
.br
.ti -1c
.RI "file \fBServoMotor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBServoMotor\&.h\fP"
.br
.in -1c
