.TH "src/peripherals/Camera.cpp" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/Camera.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Camera\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
