.TH "Camera" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Camera\&.h>\fP
.PP
Inherits cv::VideoCapture\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP (int id)"
.br
.ti -1c
.RI "cv::VideoCapture \fBgetCamera\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Camera::Camera (int id)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "cv::VideoCapture Camera::getCamera ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
