.TH "CircularQueue" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CircularQueue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CircularQueue\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCircularQueue\fP (int size)"
.br
.ti -1c
.RI "\fB~CircularQueue\fP ()"
.br
.ti -1c
.RI "void \fBenqueue\fP (int value)"
.br
.ti -1c
.RI "int \fBdequeue\fP ()"
.br
.ti -1c
.RI "void \fBdisplay\fP ()"
.br
.ti -1c
.RI "int \fBcountQueue\fP (int value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CircularQueue::CircularQueue (int size)\fC [inline]\fP"

.SS "CircularQueue::~CircularQueue ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int CircularQueue::countQueue (int value)\fC [inline]\fP"

.SS "int CircularQueue::dequeue ()\fC [inline]\fP"

.SS "void CircularQueue::display ()\fC [inline]\fP"

.SS "void CircularQueue::enqueue (int value)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
