.TH "src/thread/ControllerThread.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/thread/ControllerThread.h
.SH SYNOPSIS
.br
.PP
\fC#include 'CppThread\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBControllerThread\fP"
.br
.RI "\fBController\fP Thread to manage all child threads\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Chinmay Nagrale & Savan Agrawal 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
Create a controller thread for whole program\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
