.TH "src/controller/Controller.cpp" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/controller/Controller.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Controller\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Chinmay Nagrale 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
\fBController\fP functions for the controller class\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
