.TH "CppTimerCallback" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CppTimerCallback
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CppTimerCallback\&.h>\fP
.PP
Inherits CppTimer\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRunnable\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBregisterEventRunnable\fP (\fBRunnable\fP &h)"
.br
.ti -1c
.RI "void \fBunregisterEventRunnable\fP ()"
.br
.ti -1c
.RI "void \fBtimerEvent\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void CppTimerCallback::registerEventRunnable (\fBRunnable\fP & h)\fC [inline]\fP"

.SS "void CppTimerCallback::timerEvent ()\fC [inline]\fP"

.SS "void CppTimerCallback::unregisterEventRunnable ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
