.TH "CppTimerCallback::Runnable" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CppTimerCallback::Runnable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CppTimerCallback\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void CppTimerCallback::Runnable::run ()\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
