.TH "DoorsThread" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DoorsThread \- Doors Thread to manage doors detection functionality\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DoorsThread\&.h>\fP
.PP
Inherits \fBCppThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDoorsThread\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBjoin\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Doors Thread to manage doors detection functionality\&. 


.PP
\fBAuthor\fP
.RS 4
Chinmay Nagrale 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "DoorsThread::DoorsThread ()\fC [inline]\fP"
Contructor for our doors thread\&.
.PP
\fBParameters\fP
.RS 4
\fI\fP .RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void CppThread::join ()\fC [inline]\fP, \fC [inherited]\fP"
Waits for the thread to terminate\&. 
.SS "void CppThread::start ()\fC [inline]\fP, \fC [inherited]\fP"
Starts the thread\&. 
.SS "void DoorsThread::stop ()\fC [inline]\fP"
Stop our thread's inner functionality\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
