.TH "src/utils/EventTest/EventHandler.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/EventTest/EventHandler.h
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_map>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <any>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'EventHandler\&.tpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEventHandler\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBEvent\fP { \fBtest\fP, \fBDatasetCreatorComplete\fP, \fBDatasetTrainerComplete\fP, \fBIntruderThreadKill\fP, \fBIntruderMoodThreadKill\fP, \fBRfidAuthenticated\fP, \fBOpenGarageDoor\fP, \fBOpenedGarageDoor\fP, \fBCloseGarageDoor\fP, \fBClosedGarageDoor\fP, \fBOpenMainDoor\fP, \fBOpenedMainDoor\fP, \fBCloseMainDoor\fP, \fBClosedMainDoor\fP, \fBtest\fP, \fBDatasetCreatorComplete\fP, \fBDatasetTrainerComplete\fP, \fBIntruderThreadKill\fP, \fBIntruderMoodThreadKill\fP, \fBRfidAuthenticated\fP, \fBOpenGarageDoor\fP, \fBOpenedGarageDoor\fP, \fBCloseGarageDoor\fP, \fBClosedGarageDoor\fP, \fBOpenMainDoor\fP, \fBOpenedMainDoor\fP, \fBCloseMainDoor\fP, \fBClosedMainDoor\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBEvent\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fItest \fP\fP
.TP
\fB\fIDatasetCreatorComplete \fP\fP
.TP
\fB\fIDatasetTrainerComplete \fP\fP
.TP
\fB\fIIntruderThreadKill \fP\fP
.TP
\fB\fIIntruderMoodThreadKill \fP\fP
.TP
\fB\fIRfidAuthenticated \fP\fP
.TP
\fB\fIOpenGarageDoor \fP\fP
.TP
\fB\fIOpenedGarageDoor \fP\fP
.TP
\fB\fICloseGarageDoor \fP\fP
.TP
\fB\fIClosedGarageDoor \fP\fP
.TP
\fB\fIOpenMainDoor \fP\fP
.TP
\fB\fIOpenedMainDoor \fP\fP
.TP
\fB\fICloseMainDoor \fP\fP
.TP
\fB\fIClosedMainDoor \fP\fP
.TP
\fB\fItest \fP\fP
.TP
\fB\fIDatasetCreatorComplete \fP\fP
.TP
\fB\fIDatasetTrainerComplete \fP\fP
.TP
\fB\fIIntruderThreadKill \fP\fP
.TP
\fB\fIIntruderMoodThreadKill \fP\fP
.TP
\fB\fIRfidAuthenticated \fP\fP
.TP
\fB\fIOpenGarageDoor \fP\fP
.TP
\fB\fIOpenedGarageDoor \fP\fP
.TP
\fB\fICloseGarageDoor \fP\fP
.TP
\fB\fIClosedGarageDoor \fP\fP
.TP
\fB\fIOpenMainDoor \fP\fP
.TP
\fB\fIOpenedMainDoor \fP\fP
.TP
\fB\fICloseMainDoor \fP\fP
.TP
\fB\fIClosedMainDoor \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
