.TH "Globals" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Globals
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Globals\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetMoodSvm\fP ()"
.br
.ti -1c
.RI "cv::Ptr< cv::ml::SVM > \fBgetMoodSvm\fP ()"
.br
.ti -1c
.RI "int \fBgetGarageDoorPin\fP ()"
.br
.ti -1c
.RI "int \fBgetMainDoorPin\fP ()"
.br
.ti -1c
.RI "int \fBgetLedPin\fP ()"
.br
.ti -1c
.RI "int \fBgetLedRedPin\fP ()"
.br
.ti -1c
.RI "int \fBgetLedGreenPin\fP ()"
.br
.ti -1c
.RI "int \fBgetLedBluePin\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int Globals::getGarageDoorPin ()\fC [inline]\fP"

.SS "int Globals::getLedBluePin ()\fC [inline]\fP"

.SS "int Globals::getLedGreenPin ()\fC [inline]\fP"

.SS "int Globals::getLedPin ()\fC [inline]\fP"

.SS "int Globals::getLedRedPin ()\fC [inline]\fP"

.SS "int Globals::getMainDoorPin ()\fC [inline]\fP"

.SS "cv::Ptr< cv::ml::SVM > Globals::getMoodSvm ()\fC [inline]\fP"

.SS "void Globals::setMoodSvm ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
