.TH "src/utils/Globals.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/Globals.h
.SH SYNOPSIS
.br
.PP
\fC#include <opencv2/opencv\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGlobals\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Chinmay Nagrale 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
Anything global that will be set only once\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
