.TH "src/peripherals/I2CDriver.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/I2CDriver.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBI2CDriver\fP"
.br
.RI "I2C Driver class\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBI2C_Return\fP { \fBI2C_OK\fP = 0, \fBI2C_IOCTL_FAILED\fP = -1, \fBI2C_WRITE_FAILED\fP = -2, \fBI2C_READ_FAILED\fP = -3, \fBI2C_CRC_FAILED\fP = -4, \fBI2C_FAIL\fP = -5 }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Chinmay Nagrale 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
This file contains the class for the I2C Driver 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBI2C_Return\fP"
Return Status Enumeration 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fII2C_OK \fP\fP
.TP
\fB\fII2C_IOCTL_FAILED \fP\fP
.TP
\fB\fII2C_WRITE_FAILED \fP\fP
.TP
\fB\fII2C_READ_FAILED \fP\fP
.TP
\fB\fII2C_CRC_FAILED \fP\fP
.TP
\fB\fII2C_FAIL \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
