.TH "src/peripherals/I2CSensor.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/I2CSensor.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'I2CDriver\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBI2CSensor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Chinmay Nagrale 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
This file contains the class for the I2C Sensor 
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
