.TH "IntruderDatasetTrainer" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntruderDatasetTrainer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DatasetTrainer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntruderDatasetTrainer\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "std::string \fBextract_username\fP (std::string &input)"
.br
.ti -1c
.RI "std::map< std::string, int > \fBreadFileToMap\fP (const std::string &fileName)"
.br
.ti -1c
.RI "void \fBgenerateModel\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IntruderDatasetTrainer::IntruderDatasetTrainer ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string IntruderDatasetTrainer::extract_username (std::string & input)\fC [inline]\fP"

.SS "void IntruderDatasetTrainer::generateModel ()\fC [inline]\fP"

.SS "void IntruderDatasetTrainer::Initialize ()"
Initializes our Dataset Trainer\&.
.PP
\fBParameters\fP
.RS 4
\fI\fP .RE
.PP
return 
.SS "std::map< std::string, int > IntruderDatasetTrainer::readFileToMap (const std::string & fileName)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
