.TH "IntruderMoodThread" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntruderMoodThread
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IntruderMoodThread\&.h>\fP
.PP
Inherits \fBCppThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntruderMoodThread\fP (cv::VideoCapture camera)"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.ti -1c
.RI "void \fBrestart\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBjoin\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IntruderMoodThread::IntruderMoodThread (cv::VideoCapture camera)\fC [inline]\fP"
Contructor for our intruder mood thread\&. 
.SH "Member Function Documentation"
.PP 
.SS "void CppThread::join ()\fC [inline]\fP, \fC [inherited]\fP"
Waits for the thread to terminate\&. 
.SS "void IntruderMoodThread::restart ()\fC [inline]\fP"

.SS "void CppThread::start ()\fC [inline]\fP, \fC [inherited]\fP"
Starts the thread\&. 
.SS "void IntruderMoodThread::stop ()\fC [inline]\fP"

.SS "void IntruderMoodThread::unlock ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
