.TH "src/peripherals/LEDController.cpp" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/LEDController.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'LEDController\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Savan Agrawal 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
LED \fBController\fP CPP file to control normal and RGB ligth 
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
