.TH "LEDController" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LEDController
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LEDController\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLEDController\fP (int ledPin, int redPin, int greenPin, int bluePin)"
.br
.ti -1c
.RI "void \fBturnOnLED\fP ()"
.br
.ti -1c
.RI "void \fBturnOffLED\fP ()"
.br
.ti -1c
.RI "void \fBsetRGBColor\fP (const std::string &color)"
.br
.ti -1c
.RI "void \fBturnOffRGBLED\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LEDController::LEDController (int ledPin, int redPin, int greenPin, int bluePin)"

.SH "Member Function Documentation"
.PP 
.SS "void LEDController::setRGBColor (const std::string & color)"

.SS "void LEDController::turnOffLED ()"

.SS "void LEDController::turnOffRGBLED ()"

.SS "void LEDController::turnOnLED ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
