.TH "src/peripherals/LEDController.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/LEDController.h
.SH SYNOPSIS
.br
.PP
\fC#include <wiringPi\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLEDController\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Savan Agrawal 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
LED \fBController\fP header file to control normal and RGB ligth 
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
