.TH "src/dependencies/spidevpp/apps/loopback_example_app/main.cc" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dependencies/spidevpp/apps/loopback_example_app/main.cc
.SH SYNOPSIS
.br
.PP
\fC#include <spidevpp/spi\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
