.TH "src/peripherals/MFRC522.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/MFRC522.h
.SH SYNOPSIS
.br
.PP
\fC#include 'bcm2835/ispi\&.h'\fP
.br
\fC#include 'bcm2835/igpio\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmfrc522::MFRC522\fP"
.br
.ti -1c
.RI "struct \fBmfrc522::MFRC522::Uid\fP"
.br
.ti -1c
.RI "struct \fBmfrc522::MFRC522::MIFARE_Key\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmfrc522\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
