.TH "mfrc522::ISpi" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mfrc522::ISpi
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ispi\&.h>\fP
.PP
Inherited by \fBBcmSpi\fP, and \fBSpidev\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBwrite\fP (char *pData, size_t len)=0"
.br
.ti -1c
.RI "virtual void \fBread\fP (char *pData, size_t len)=0"
.br
.ti -1c
.RI "virtual void \fBwriteRead\fP (char *pData, size_t len)=0"
.br
.ti -1c
.RI "virtual char \fBwriteRead\fP (char data)=0"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (char *pData, size_t len)=0"
.br
.ti -1c
.RI "virtual void \fBread\fP (char *pData, size_t len)=0"
.br
.ti -1c
.RI "virtual void \fBwriteRead\fP (char *pData, size_t len)=0"
.br
.ti -1c
.RI "virtual char \fBwriteRead\fP (char data)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void mfrc522::ISpi::read (char * pData, size_t len)\fC [pure virtual]\fP"

.PP
Implemented in \fBBcmSpi\fP, and \fBSpidev\fP\&.
.SS "virtual void mfrc522::ISpi::read (char * pData, size_t len)\fC [pure virtual]\fP"

.PP
Implemented in \fBBcmSpi\fP, and \fBSpidev\fP\&.
.SS "virtual void mfrc522::ISpi::write (char * pData, size_t len)\fC [pure virtual]\fP"

.PP
Implemented in \fBBcmSpi\fP, and \fBSpidev\fP\&.
.SS "virtual void mfrc522::ISpi::write (char * pData, size_t len)\fC [pure virtual]\fP"

.PP
Implemented in \fBBcmSpi\fP, and \fBSpidev\fP\&.
.SS "virtual void mfrc522::ISpi::writeRead (char * pData, size_t len)\fC [pure virtual]\fP"

.PP
Implemented in \fBBcmSpi\fP, and \fBSpidev\fP\&.
.SS "virtual void mfrc522::ISpi::writeRead (char * pData, size_t len)\fC [pure virtual]\fP"

.PP
Implemented in \fBBcmSpi\fP, and \fBSpidev\fP\&.
.SS "virtual char mfrc522::ISpi::writeRead (char data)\fC [pure virtual]\fP"

.PP
Implemented in \fBBcmSpi\fP, and \fBSpidev\fP\&.
.SS "virtual char mfrc522::ISpi::writeRead (char data)\fC [pure virtual]\fP"

.PP
Implemented in \fBBcmSpi\fP, and \fBSpidev\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
