.TH "src/dependencies/mfrc522/mfrc522.cc" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dependencies/mfrc522/mfrc522.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'mfrc522\&.h'\fP
.br
\fC#include <linux/types\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <thread>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmfrc522\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
