.TH "src/mood-detection/MoodDetection.cpp" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mood-detection/MoodDetection.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'MoodDetection\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Savan Agrawal & Chinmay Nagrale 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
Functions for mood detection\&.
.PP
https://opencv.org/ 
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
