.TH "src/thread/mood-detection/MoodThread.cpp" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/thread/mood-detection/MoodThread.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'MoodDetection\&.h'\fP
.br
\fC#include 'MoodThread\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <thread>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEVENT_OP_CODES\fP { \fBEXIT_APPLICATION\fP = 255, \fBEXIT_APPLICATION\fP = 255, \fBEXIT_APPLICATION\fP = 255, \fBEXIT_APPLICATION\fP = 255, \fBEXIT_APPLICATION\fP = 255, \fBEXIT_APPLICATION\fP = 255, \fBEXIT_APPLICATION\fP = 255, \fBEXIT_APPLICATION\fP = 255 }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Chinmay Nagrale 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
Functions related to mood detection thread\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBEVENT_OP_CODES\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEXIT_APPLICATION \fP\fP
.TP
\fB\fIEXIT_APPLICATION \fP\fP
.TP
\fB\fIEXIT_APPLICATION \fP\fP
.TP
\fB\fIEXIT_APPLICATION \fP\fP
.TP
\fB\fIEXIT_APPLICATION \fP\fP
.TP
\fB\fIEXIT_APPLICATION \fP\fP
.TP
\fB\fIEXIT_APPLICATION \fP\fP
.TP
\fB\fIEXIT_APPLICATION \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
