.TH "RFID" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RFID
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RFID\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRFID\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "void \fBsetMfrc\fP (\fBmfrc522::MFRC522\fP *mfrc)"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RFID::RFID ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void RFID::Initialize ()"

.SS "void RFID::setMfrc (\fBmfrc522::MFRC522\fP * mfrc)\fC [inline]\fP"

.SS "void RFID::start ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
