.TH "src/peripherals/ServoMotor.cpp" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/ServoMotor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ServoMotor\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <pigpio\&.h>\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Savan Agrawal 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
Servo Moto cpp file to take pin and angle of motor 
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
