.TH "ServoMotor" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServoMotor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ServoMotor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServoMotor\fP (int pin)"
.br
.ti -1c
.RI "\fB~ServoMotor\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP (int angle)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ServoMotor::ServoMotor (int pin)"

.SS "ServoMotor::~ServoMotor ()"

.SH "Member Function Documentation"
.PP 
.SS "void ServoMotor::write (int angle)"


.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
