.TH "src/peripherals/ServoMotor.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/ServoMotor.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBServoMotor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Savan Agrawal 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1
.RE
.PP
Servo Moto Header file to take pin and angle of motor 
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
