.TH "src/dependencies/spidevpp/libs/spidevpp/spi.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/dependencies/spidevpp/libs/spidevpp/spi.h
.SH SYNOPSIS
.br
.PP
\fC#include <linux/spi/spidev\&.h>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBspidevpp::Spi\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBspidevpp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Stream > Stream & \fBspidevpp::operator<<\fP (Stream &out, const Spi &spi)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
