.TH "spidevpp" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spidevpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGpio\fP"
.br
.ti -1c
.RI "class \fBSpi\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Stream > Stream & \fBoperator<<\fP (Stream &out, const \fBSpi\fP &spi)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class Stream > Stream & spidevpp::operator<< (Stream & out, const \fBSpi\fP & spi)"

.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
