.TH "src/peripherals/spi/sys_gpio_impl.h" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/peripherals/spi/sys_gpio_impl.h
.SH SYNOPSIS
.br
.PP
\fC#include <mfrc522/igpio\&.h>\fP
.br
\fC#include <spidevpp/gpio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSysGpio\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
