.TH "Threads" 3 "Tue Apr 25 2023" "Version v.1.0" "HomeGPT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Threads
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Threads\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetIntruderThread\fP (\fBIntruderThread\fP *it)"
.br
.ti -1c
.RI "\fBIntruderThread\fP \fBgetIntruderThread\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBIntruderThread\fP Threads::getIntruderThread ()\fC [inline]\fP"

.SS "void Threads::setIntruderThread (\fBIntruderThread\fP * it)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for HomeGPT from the source code\&.
