name: run-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COVERAGE_DATA_PATH: extras/coverage-data/coverage.info

    steps:
      - uses: actions/checkout@v3

      - uses: arduino/cpp-test-action@main
        with:
          coverage-data-path: ${{ env.COVERAGE_DATA_PATH }}

      # Optional: upload coverage report to codecov.io
      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.COVERAGE_DATA_PATH }}
